import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";

import { Toaster } from "../components/ui/sonner";
import { Modals } from "../components/modals";
import { ConvexClientProvider } from "../components/conex-client-provider";

import "./globals.css";
import { JotaiProvider } from "../components/jotai-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
      <html lang="en">
        <body className={inter.className}>
          <ConvexClientProvider>
            <JotaiProvider>
            <Toaster/>
            <Modals/>
            {children}
            </JotaiProvider>
          </ConvexClientProvider>
          </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  );
}
